// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhn0FfkV2wCEuELjoFaUUKOSm97qVQ8qw',
    appId: '1:1041620136015:web:f43fa17e6407dc8a8b3a3a',
    messagingSenderId: '1041620136015',
    projectId: 'sensora-01',
    authDomain: 'sensora-01.firebaseapp.com',
    storageBucket: 'sensora-01.firebasestorage.app',
    measurementId: 'G-2PSWRQBRV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVnp67w4VWVMgnjpQYZj60CZtxkPcbVk8',
    appId: '1:1041620136015:android:71be598e226affbe8b3a3a',
    messagingSenderId: '1041620136015',
    projectId: 'sensora-01',
    storageBucket: 'sensora-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj_Sx9Tz22Etnk_c0RE3wf-SxGjeEZvXM',
    appId: '1:1041620136015:ios:dc60ab222ac67e688b3a3a',
    messagingSenderId: '1041620136015',
    projectId: 'sensora-01',
    storageBucket: 'sensora-01.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj_Sx9Tz22Etnk_c0RE3wf-SxGjeEZvXM',
    appId: '1:1041620136015:ios:dc60ab222ac67e688b3a3a',
    messagingSenderId: '1041620136015',
    projectId: 'sensora-01',
    storageBucket: 'sensora-01.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhn0FfkV2wCEuELjoFaUUKOSm97qVQ8qw',
    appId: '1:1041620136015:web:7d4390eacef8d8a08b3a3a',
    messagingSenderId: '1041620136015',
    projectId: 'sensora-01',
    authDomain: 'sensora-01.firebaseapp.com',
    storageBucket: 'sensora-01.firebasestorage.app',
    measurementId: 'G-VBX1LK0R8H',
  );
}
